name: "Github Version Creator"
description: "Generate a new variable with the new version"
inputs:
  method:
    description: "Which method should be used to generate the new Version"
    required: true
    default: "auto"
  path:
    description: "Path to a JSON file to read from"
    required: true
    default: "./"
outputs:
  version:
    description: "New version"
  title:
    description: "Commit title that created this action"
  description:
    description: "Commit description that created this action"
  is_new_version:
    description: "True or False if the version output is different than the latest tag"
runs:
  using: "node12"
  main: "lib/index.js"
